---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-java
  labels:
    app: tomcat-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-java
  template:
    metadata:
      labels:
        app: tomcat-java
    spec:
      containers:
      - name: tomcat-java
        image: jpetstore.azurecr.io/pakak/jpetstore:v1.12
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: tomcat-service-java
spec:
  type: LoadBalancer
  selector:
    app: tomcat-java
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
